import { Food } from './food.ts';
import { generateId } from './id.ts';

export const mockFood: Food[] = [
  {
    id: generateId(),
    name: 'Pizza',
    fat: 10,
    protein: 20,
    carbs: 30,
    kcal: 400,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Apple',
    fat: 1,
    protein: 1,
    carbs: 10,
    kcal: 50,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Chicken',
    fat: 5,
    protein: 30,
    carbs: 0,
    kcal: 200,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Pasta',
    fat: 5,
    protein: 10,
    carbs: 50,
    kcal: 300,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Banana',
    fat: 1,
    protein: 1,
    carbs: 20,
    kcal: 100,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Beef',
    fat: 10,
    protein: 40,
    carbs: 0,
    kcal: 300,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Rice',
    fat: 1,
    protein: 5,
    carbs: 50,
    kcal: 200,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Orange',
    fat: 1,
    protein: 1,
    carbs: 10,
    kcal: 50,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Pork',
    fat: 15,
    protein: 30,
    carbs: 0,
    kcal: 250,
    weight: 100,
  },
  {
    id: generateId(),
    name: 'Spaghetti',
    fat: 5,
    protein: 10,
    carbs: 50,
    kcal: 300,
    weight: 100,
  },
];
